/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/wpONfJACWML
 */
import Link from "next/link"

export function Footer() {
  return (
    (<footer className="w-full py-12 bg-gray-900 text-white">
      <div
        className="container mx-auto px-4 md:px-6 lg:px-8 grid gap-8 md:grid-cols-3">
          <div>
          <Link className="flex items-center" href="/">
            <div className="w-24 h-20 object-cover" >
              <img src="/icons/logo.png" alt="" />
            </div>
          </Link>
        </div>
        <div>
          <h4 className="text-lg font-semibold mb-4">Contact Information</h4>
          <p className="text-sm mb-2">Aryaman Infotech, Ranchi, Jharkhand, 12345</p>
          <p className="text-sm mb-2">Phone: +91 987654321</p>
          <p className="text-sm">Email: aryainfo@gmail.com</p>
        </div>
        {/* <div>
          <h4 className="text-lg font-semibold mb-4">Social Media</h4>
          <div className="flex space-x-4">
            <Link href="#">
              <LinkedinIcon className="h-6 w-6 text-white hover:text-gray-300" />
            </Link>
            <Link href="#">
              <TwitterIcon className="h-6 w-6 text-white hover:text-gray-300" />
            </Link>
            <Link href="#">
              <GithubIcon className="h-6 w-6 text-white hover:text-gray-300" />
            </Link>
          </div>
        </div> */}
        <div>
          <h4 className="text-lg font-semibold mb-4">Quick Links</h4>
          <ul className="space-y-2 text-sm">

            <li>
              <Link className="hover:underline" href="#service">
                Services
              </Link>
            </li>

            <li>
              <Link className="hover:underline" href="#">
                Privacy Policy
              </Link>
            </li>
          </ul>
        </div>
        
      </div>
    </footer>)
  );
}


