/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/T8E92viZbzp
 */


export function HeroSection() {
  return (
    (<section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container px-4 md:px-6">
        <div
          className="flex flex-col md:flex-row justify-between">
          <div className="flex flex-col justify-center space-y-4">
            <div className="space-y-2">
              <p
                className="text-lg font-semibold text-gray-500 md:text-xl dark:text-gray-400">
                Welcome to Aryaman Infotech
              </p>
              <h1 className="text-3xl font-bold tracking-tighter sm:text-6xl">
              One-Stop for <br /> Comprehensive  IT Services  <br />and Solutions
              </h1>
              <p
                className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                At Aryaman Infotech, we specialize in providing cutting-edge IT solutions to meet the diverse needs of businesses. With a focus on innovation and reliability, we offer a wide range of services to ensure that your technology infrastructure remains robust and efficient.
              </p>
            </div>
          </div>
          <img
            alt="Hero"
            className="mx-auto  overflow-hidden rounded-xl object-cover object-center  "
            height="700"
            src="/hero-bg.svg"
            width="700" />
        </div>
      </div>
    </section>)
  );
}
